version: '2'
services:
  db:
    image: mysql:5.6
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "4306:3306"

  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/shares
      - public-data:/shares/public
      - tmp-data:/shares/tmp
      - log-data:/shares/log
  
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/shares/public
      - tmp-data:/shares/tmp
    ports:
      - "80:80"

volumes:
  mysql-data:
  bundle:
  public-data:
  tmp-data:
  log-data: