version: '2'
services:
  db:
    extends:
      file: docker-compose.yml
      service: db
      
  app:
    extends:
      file: docker-compose.yml
      service: app
    volumes:
      - .:/shares
      - bundle:/usr/local/bundle
    links:
      - db
    environment:
      RAILS_ENV: production

  web:
    extends:
      file: docker-compose.yml
      service: web
    depends_on:
      - app
volumes:
  mysql-data:
  bundle:
  public-data:
  tmp-data:
  log-data: