version: '2'
services:
  db:
    extends:
      file: docker-compose.yml
      service: db
      
  app:
    extends:
      file: docker-compose.yml
      service: app
    tty: true
    stdin_open: true
    links:
      - db
    environment:
      RAILS_ENV: production

  web:
    extends:
      file: docker-compose.yml
      service: web
    depends_on:
      - app
volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data: